In [2]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [3]:
customers = catalog.load("customers")

[05/15/25 20:13:48] INFO     Loading data from customers (CSVDataset)...                        ]8;id=133797;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=760720;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

In [4]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [5]:
orders = catalog.load("orders")

[05/15/25 20:13:49] INFO     Loading data from orders (CSVDataset)...                           ]8;id=758299;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=607567;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

In [6]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [7]:
products = catalog.load("products")

                    INFO     Loading data from products (CSVDataset)...                         ]8;id=925822;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=915749;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

In [8]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [9]:
order_items = catalog.load("order_items")
order_items

                    INFO     Loading data from order_items (CSVDataset)...                      ]8;id=356204;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=770943;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [10]:
order_payments = catalog.load("order_payments")
order_payments

                    INFO     Loading data from order_payments (CSVDataset)...                   ]8;id=132232;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=647932;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [11]:
order_reviews = catalog.load("order_reviews")
order_reviews

                    INFO     Loading data from order_reviews (CSVDataset)...                    ]8;id=973134;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=533097;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [12]:
sellers = catalog.load("sellers")
sellers

[05/15/25 20:13:50] INFO     Loading data from sellers (CSVDataset)...                          ]8;id=439117;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=441412;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [13]:
geolocation = catalog.load("geolocation")
geolocation

                    INFO     Loading data from geolocation (CSVDataset)...                      ]8;id=34977;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=399345;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [14]:
product_category_name_translation = catalog.load("product_category_name_translation")
product_category_name_translation

                    INFO     Loading data from product_category_name_translation                ]8;id=920382;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=650988;file://c:\Users\Usuario\anaconda3\Lib\site-packages\kedro\io\data_catalog.py#401\401]8;;\
                             (CSVDataset)...

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [15]:
geolocation = geolocation.rename(
    columns={"geolocation_zip_code_prefix": "zip_code_prefix"}
)

geo_unico = geolocation.drop_duplicates(
    subset=["zip_code_prefix"],
    keep="first"
)

In [16]:
sellers = sellers.rename(
    columns={"seller_zip_code_prefix": "zip_code_prefix"}
)

In [17]:
df = (
    orders
    .merge(customers,     on="customer_id",    how="left")
    .merge(order_payments, on="order_id",       how="left")
    .merge(order_reviews,  on="order_id",       how="left")
    .merge(order_items,    on="order_id",       how="left")
    .merge(products,       on="product_id",     how="left")
    .merge(sellers,        on="seller_id",      how="left")
    .merge(geo_unico,     on="zip_code_prefix",how="left")
    .merge(product_category_name_translation,      on="product_category_name", how="left")
)

In [18]:
print(df.shape)
df

(119143, 44)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_height_cm,product_width_cm,zip_code_prefix,seller_city,seller_state,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,-23.680114,-46.452454,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,-23.680114,-46.452454,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,-23.680114,-46.452454,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,13.0,19.0,31570.0,belo horizonte,SP,-19.810119,-43.984727,belo horizonte,MG,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,19.0,21.0,14840.0,guariba,SP,-21.362358,-48.232976,guariba,SP,auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,10.0,40.0,17602.0,tupa,SP,-21.935321,-50.497562,tupa,SP,baby
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,90.0,22.0,8290.0,sao paulo,SP,-23.551013,-46.448489,sao paulo,SP,home_appliances_2
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,20.0,20.0,37175.0,ilicinea,MG,-20.944706,-45.827098,ilicinea,MG,computers_accessories
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,20.0,20.0,37175.0,ilicinea,MG,-20.944706,-45.827098,ilicinea,MG,computers_accessories
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,7.0,15.0,14407.0,franca,SP,-20.502342,-47.421590,franca,SP,health_beauty

In [20]:
print(df.shape)

(119143, 44)

In [21]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  payment_sequential             119140 non-null  float64
 13  payment_type                   119140 non-null  object
 14  payment_installments           119140 non-null  float64
 15  payment_value                  119140 non-null  float64
 16  review_id                      118146 non-null  object
 17  review_score                   118146 non-null  float64
 18  review_comment_title           13989 non-null   object
 19  review_comment_message         50245 non-null   object
 20  review_creation_date           118146 non-null  object
 21  review_answer_timestamp        118146 non-null  object
 22  order_item_id                  118310 non-null  float64
 23  product_id                     118310 non-null  object
 24  seller_id                      118310 non-null  object
 25  shipping_limit_date            118310 non-null  object
 26  price                          118310 non-null  float64
 27  freight_value                  118310 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  zip_code_prefix                118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  geolocation_lat                118045 non-null  float64
 40  geolocation_lng                118045 non-null  float64
 41  geolocation_city               118045 non-null  object
 42  geolocation_state              118045 non-null  object
 43  product_category_name_english  116576 non-null  object
dtypes: float64(17), int64(1), object(26)
memory usage: 40.0+ MB
None

In [22]:
print(df.describe())

       customer_zip_code_prefix  payment_sequential  payment_installments  \
count             119143.000000       119140.000000         119140.000000
mean               35033.451298            1.094737              2.941246
std                29823.198969            0.730141              2.777848
min                 1003.000000            1.000000              0.000000
25%                11250.000000            1.000000              1.000000
50%                24240.000000            1.000000              2.000000
75%                58475.000000            1.000000              4.000000
max                99990.000000           29.000000             24.000000

       payment_value   review_score  order_item_id          price  \
count  119140.000000  118146.000000  118310.000000  118310.000000
mean      172.735135       4.015582       1.196543     120.646603
std       267.776077       1.400436       0.699489     184.109691
min         0.000000       1.000000       1.000000       0.850000
25%        60.850000       4.000000       1.000000      39.900000
50%       108.160000       5.000000       1.000000      74.900000
75%       189.240000       5.000000       1.000000     134.900000
max     13664.080000       5.000000      21.000000    6735.000000

       freight_value  product_name_lenght  product_description_lenght  \
count  118310.000000        116601.000000               116601.000000
mean       20.032387            48.767498                  785.967822
std        15.836850            10.033540                  652.584121
min         0.000000             5.000000                    4.000000
25%        13.080000            42.000000                  346.000000
50%        16.280000            52.000000                  600.000000
75%        21.180000            57.000000                  983.000000
max       409.680000            76.000000                 3992.000000

       product_photos_qty  product_weight_g  product_length_cm  \
count       116601.000000     118290.000000      118290.000000
mean             2.205161       2112.250740          30.265145
std              1.717452       3786.695111          16.189367
min              1.000000          0.000000           7.000000
25%              1.000000        300.000000          18.000000
50%              1.000000        700.000000          25.000000
75%              3.000000       1800.000000          38.000000
max             20.000000      40425.000000         105.000000

       product_height_cm  product_width_cm  zip_code_prefix  geolocation_lat  \
count      118290.000000     118290.000000    118310.000000    118045.000000
mean           16.619706         23.074799     24442.410413       -22.797849
std            13.453584         11.749139     27573.004511         2.690420
min             2.000000          6.000000      1001.000000       -36.605374
25%             8.000000         15.000000      6429.000000       -23.609026
50%            13.000000         20.000000     13660.000000       -23.422076
75%            20.000000         30.000000     27972.000000       -21.766477
max           105.000000        118.000000     99730.000000        -2.546079

       geolocation_lng
count    118045.000000
mean        -47.238603
std           2.341104
min         -67.809656
25%         -48.831547
50%         -46.755211
75%         -46.518082
max         -34.847856

In [27]:

print(df.isnull().sum().sort_values())

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_estimated_delivery_date         0
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
payment_value                         3
payment_installments                  3
payment_sequential                    3
payment_type                          3
order_approved_at                   177
shipping_limit_date                 833
seller_state                        833
zip_code_prefix                     833
freight_value                       833
order_item_id                       833
product_id                          833
seller_id                           833
seller_city                         833
price                               833
product_width_cm                    853
product_height_cm                   853
product_length_cm                   853
product_weight_g                    853
review_answer_timestamp             997
review_creation_date                997
review_score                        997
review_id                           997
geolocation_lat                    1098
geolocation_lng                    1098
geolocation_city                   1098
geolocation_state                  1098
order_delivered_carrier_date       2086
product_category_name              2542
product_name_lenght                2542
product_description_lenght         2542
product_photos_qty                 2542
product_category_name_english      2567
order_delivered_customer_date      3421
review_comment_message            68898
review_comment_title             105154
dtype: int64

In [28]:
print(df.duplicated().sum().sort.values())

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 print(df.duplicated().sum().sort.values())                                                   │
│   2                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'builtin_function_or_method' object has no attribute 'values'